### ISSUE TITLE
Pull gameids

### ISSUE THREAD

**Issue by MichaelWS** [bradleyfay/NBAStats#2]
Is there any way to get a list of gameid's ?

**Comment by bradleyfay** [comment]
I'm in the process of completely rebuilding this package under a new name, py-Goldsberry. 

Within the package, I've gone through and created a list of gameids. That table is included in the development version as of now. I hope to merge it into the next version sometime next week. 

In addition to gameids, it has many more data pulls and is better organized (in my opinion). You should check it out. You can install a beta version using pip install py-goldsberry. There are some known bugs I'm in the process of fixing and a lot more additional functionality I want to add but everything that's in nbastats is already there.

**Comment by Mpellet771** [comment]
This is great! The season is coming up and I look forward to trying out your program.

Thanks for all the updates to us all.

Marianne

**Comment by bradleyfay** [comment]
See issue #7
