### ISSUE TITLE
I hope to use the boxscores class

### ISSUE THREAD

**Issue by Mpellet771** [bradleyfay/NBAStats#3]
I may be missing how to do this, but I'm hoping to get to use the boxscores class in this module. Do you mind sharing documentation for it? this is a terrific module.

**Comment by bradleyfay** [comment]
Hi,

I just went through and put together the loop that I had previously mentioned to you. I'm not sure if you ever figured it out, but I wanted to share a link to an IPython notebook that has the code in it to pull all the box scores from 2013-14 through about the All-star break of 2014-15 and put it into a single dataframe.

[http://nbviewer.ipython.org/urls/dl.dropbox.com/s/otqqmyyihi8rwju/data-pull-MKT-591-Sports-Analytics.ipynb?dl=0](http://nbviewer.ipython.org/urls/dl.dropbox.com/s/otqqmyyihi8rwju/data-pull-MKT-591-Sports-Analytics.ipynb?dl=0)

Just so you know, this loop took over 6 hours to run (you can see the stats and a counter in the notebook).

If you want to do different seasons, all you need to do is change the `213` to `212`, `211`, etc... depending on the year of the season you are interested in.

**Comment by Mpellet771** [comment]
Hi, Bradley,

Thank you! I haven’t been able to do much more, even though I visited your GitHub site a few more times. I appreciate this additional script and will try it this weekend.

 

--Marianne
